name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.2
      - name: Install dependencies
        run: yarn install

      - name: Packages build
        run: yarn packages:build

      - name: Run linting
        run: yarn lint
